{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
data:
  NODE_ENV: {{ .Values.backend.config.nodeEnv | quote }}
  PORT: {{ .Values.backend.config.port | quote }}
  DB_NAME: {{ .Values.backend.config.dbName | quote }}
  LOG_LEVEL: {{ .Values.backend.config.logLevel | quote }}
  # MongoDB connection (non-sensitive part)
  MONGODB_HOST: {{ .Values.mongodb.name | quote }}
  MONGODB_PORT: {{ .Values.mongodb.service.port | quote }}
  MONGODB_DATABASE: {{ .Values.mongodb.config.database | quote }}
{{- end }}