# helm-charts/devops-app/templates/backend/configmap.yaml
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
data:
  NODE_ENV: {{ .Values.backend.config.nodeEnv }}
  PORT: "{{ .Values.backend.config.port }}"
  LOG_LEVEL: {{ .Values.backend.config.logLevel }}
  # Add other config values as needed
{{- end }}