{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app: {{ .Values.backend.name }}
    spec:
      securityContext:
        {{- toYaml .Values.backend.securityContext | nindent 8 }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.backend.serviceAccount.name }}
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.backend.name }}-config
        env:
        {{- if .Values.backend.secrets.enabled }}
        - name: {{ .Values.backend.secrets.jwtSecretKey }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secrets
              key: {{ .Values.backend.secrets.jwtSecretKey }}
        - name: {{ .Values.backend.secrets.mongoUriKey }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.name }}-secrets
              key: {{ .Values.backend.secrets.mongoUriKey }}
        {{- end }}
        {{- if .Values.backend.jaeger.enabled }}
        # Jaeger Tracing Configuration
        - name: JAEGER_SERVICE_NAME
          value: {{ .Values.backend.jaeger.serviceName }}
        - name: JAEGER_AGENT_HOST
          value: {{ .Values.backend.jaeger.agentHost }}
        - name: JAEGER_AGENT_PORT
          value: {{ .Values.backend.jaeger.agentPort }}
        - name: JAEGER_SAMPLER_TYPE
          value: {{ .Values.backend.jaeger.samplerType }}
        - name: JAEGER_SAMPLER_PARAM
          value: {{ .Values.backend.jaeger.samplerParam }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.backend.containerSecurityContext | nindent 12 }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}