# helm-charts/devops-app/templates/backend/deployment.yaml
{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.backend.name }}
        app: {{ .Values.backend.name }}  # For compatibility with existing services
    spec:
      securityContext:
        {{- toYaml .Values.backend.securityContext | nindent 8 }}
      serviceAccountName: {{ .Values.backend.name }}-sa
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.config.nodeEnv }}
        - name: PORT
          value: "{{ .Values.backend.config.port }}"
        - name: LOG_LEVEL
          value: {{ .Values.backend.config.logLevel }}
        # Environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: {{ .Values.backend.name }}-config
        # Secrets (will be added in afternoon session)
        securityContext:
          {{- toYaml .Values.backend.containerSecurityContext | nindent 12 }}
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: app-logs
          mountPath: /app/logs
        resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: app-logs
        emptyDir: {}
{{- end }}