{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: grafana
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.monitoring.grafana.image.repository }}:{{ .Values.monitoring.grafana.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "devops-app.fullname" . }}-grafana-secret
              key: admin-password
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          {{- toYaml .Values.monitoring.grafana.resources | nindent 12 }}
      volumes:
      - name: grafana-datasources
        configMap:
          name: {{ include "devops-app.fullname" . }}-grafana-datasources
      - name: grafana-dashboards-config
        configMap:
          name: {{ include "devops-app.fullname" . }}-grafana-dashboards
      - name: grafana-storage
        {{- if .Values.monitoring.grafana.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "devops-app.fullname" . }}-grafana-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}-grafana
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
    app: grafana
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-app.fullname" . }}-grafana-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
{{- end }}