{{- if and .Values.monitoring.enabled .Values.monitoring.promtail.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devops-app.fullname" . }}-promtail
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "devops-app.fullname" . }}-promtail
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devops-app.fullname" . }}-promtail
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "devops-app.fullname" . }}-promtail
subjects:
- kind: ServiceAccount
  name: {{ include "devops-app.fullname" . }}-promtail
  namespace: {{ .Values.global.namespace }}
{{- end }}