{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app.fullname" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: prometheus
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app: prometheus
    spec:
      serviceAccountName: {{ include "devops-app.fullname" . }}-prometheus
      containers:
      - name: prometheus
        image: {{ .Values.monitoring.prometheus.image.repository }}:{{ .Values.monitoring.prometheus.image.tag }}
        ports:
        - containerPort: 9090
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus/'
          - '--web.console.libraries=/etc/prometheus/console_libraries'
          - '--web.console.templates=/etc/prometheus/consoles'
          - '--storage.tsdb.retention.time={{ .Values.monitoring.prometheus.retention | default "15d" }}'
          - '--web.enable-lifecycle'
          - '--web.route-prefix=/'
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
        - name: prometheus-storage
          mountPath: /prometheus/
        resources:
          {{- toYaml .Values.monitoring.prometheus.resources | nindent 12 }}
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ include "devops-app.fullname" . }}-prometheus-config
      - name: prometheus-storage
        {{- if .Values.monitoring.prometheus.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "devops-app.fullname" . }}-prometheus-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app.fullname" . }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    {{- include "devops-app.selectorLabels" . | nindent 4 }}
    app: prometheus
{{- end }}