{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
{{- if .Values.backend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-app.fullname" . }}-backend-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.backend.name }}
  endpoints:
  - port: http
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
    path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
    scheme: http
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-app.fullname" . }}-frontend-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.frontend.name }}
  endpoints:
  - port: http
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
    path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
    scheme: http
---
{{- end }}
{{- if .Values.mongodb.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-app.fullname" . }}-mongodb-monitor
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.mongodb.name }}
  endpoints:
  - port: mongodb
    interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
    path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
    scheme: http
{{- end }}
{{- end }}