{{- if .Values.rbac.create }}
# Service Account for MongoDB
{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mongodb.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
automountServiceAccountToken: false
---
{{- end }}

# Service Account for Backend
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
automountServiceAccountToken: true
---
{{- end }}

# Service Account for Frontend
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
{{- end }}
{{- end }}