{{- if .Values.autoscaling.enabled }}
{{- if .Values.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "devops-app.fullname" . }}-backend-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.name }}
  minReplicas: {{ .Values.autoscaling.backend.minReplicas | default 2 }}
  maxReplicas: {{ .Values.autoscaling.backend.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.autoscaling.backend.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.backend.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.backend.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.backend.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.autoscaling.backend.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.backend.behavior | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "devops-app.fullname" . }}-frontend-hpa
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontend.name }}
  minReplicas: {{ .Values.autoscaling.frontend.minReplicas | default 2 }}
  maxReplicas: {{ .Values.autoscaling.frontend.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.autoscaling.frontend.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.frontend.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.frontend.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.frontend.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.autoscaling.frontend.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.frontend.behavior | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}