# azure-pipelines-ultra-simple.yml
trigger:
  branches:
    include: [develop, qa, main]

variables:
  azureServiceConnection: "azure-federated-identity"

stages:
  - stage: Test_Auth_Only
    jobs:
      - job: TestAuth
        pool:
          name: "devopsjourney"
        steps:
          - task: AzureCLI@2
            displayName: "Test Azure Authentication"
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "🔐 Testing Azure AD federated authentication..."
                az account show
                echo "✅ Authentication successful!"
                echo "Branch: $(Build.SourceBranch)"
                echo "This proves federated identity is working!"
