{{- if .Values.gatekeeper.enabled }}
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: {{ include "devops-app.fullname" . }}-security-policy
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  crd:
    spec:
      names:
        kind: SecurityPolicy
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedUsers:
              type: array
              items:
                type: integer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package securitypolicy
        
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          container.securityContext.runAsUser == 0
          msg := "Containers must not run as root user"
        }
        
        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          container.securityContext.allowPrivilegeEscalation == true
          msg := "Privilege escalation not allowed"
        }
---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "devops-app.fullname" . }}-security-constraint
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  match:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
      namespaces: [{{ .Values.global.namespace | quote }}]
{{- end }}