{{- if .Values.podSecurityStandards.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce | default "restricted" }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit | default "restricted" }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn | default "restricted" }}
{{- end }}