{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "devops-app.fullname" . }}-quota
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- if .Values.resourceQuota.scopeSelector }}
  scopeSelector:
    {{- toYaml .Values.resourceQuota.scopeSelector | nindent 4 }}
{{- end }}
{{- if .Values.resourceQuota.scopes }}
  scopes:
    {{- toYaml .Values.resourceQuota.scopes | nindent 4 }}
{{- end }}
{{- end }}