apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  NODE_ENV: "development"
  PORT: "5000"
  DB_NAME: "devops-app"
  LOG_LEVEL: "info"
  # Add any non-sensitive configuration here