apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: application-alerts
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
    - name: app.rules
      rules:
        - alert: BackendDown
          expr: up{job="backend"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Backend service down"
            description: "The backend service is unreachable for over 1 minute."
        - alert: HighMemory
          expr: container_memory_usage_bytes{container!=""} / container_spec_memory_limit_bytes > 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage"
            description: "{{ $labels.container }} in {{ $labels.namespace }} exceeds 90% memory usage."
