apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000 # Choose an available port 30000-32767
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
