# jaeger-agent-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:1.52.0
          ports:
            - containerPort: 6831
              protocol: UDP
              hostPort: 6831
            - containerPort: 6832
              protocol: UDP
              hostPort: 6832
            - containerPort: 5778
              protocol: TCP
              hostPort: 5778
          command:
            - "/go/bin/agent-linux"
          args:
            - "--reporter.grpc.host-port=jaeger-simple-collector.monitoring:14250"
            - "--log-level=info"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      hostNetwork: true
      serviceAccountName: jaeger-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-agent
  namespace: monitoring
