# jaeger-simple.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-simple
  namespace: monitoring # Deploy in monitoring namespace
spec:
  strategy: allInOne

  allInOne:
    image: jaegertracing/all-in-one:1.52.0

    options:
      memory:
        max-traces: 100000

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

  storage:
    type: memory

  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1.0
