# jaeger-all-in-one.yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.52.0
    options:
      memory:
        max-traces: 100000
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
  storage:
    type: memory
  ingress:
    enabled: true
  # Service configuration moved to a separate Service manifest

---
# jaeger-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
  namespace: monitoring
  labels:
    app: jaeger
    app.kubernetes.io/component: all-in-one
spec:
  type: NodePort
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
      nodePort: 32086
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one
