# simple-prometheus-values.yaml
prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    # No persistent storage - uses emptyDir
    storageSpec: {}

grafana:
  enabled: true
  adminPassword: "admin123"

  # Expose Grafana via NodePort
  service:
    type: NodePort
    nodePort: 32000
    port: 80
    targetPort: 3000

  # No persistence for simplicity
  persistence:
    enabled: false

  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

# Disable AlertManager
alertmanager:
  enabled: false

# Keep basic exporters for metrics
nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

# Disable default rules and alerts
defaultRules:
  create: false

# Keep Prometheus Operator but minimal
prometheusOperator:
  enabled: true
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
