# Tester Role - Read and update in test namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-limited-access
  namespace: test
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-limited-access-binding
  namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-limited-access
subjects:
  - kind: ServiceAccount
    name: test-user
    namespace: test
