apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-user
  namespace: dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user
  namespace: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-user
  namespace: prod
