{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mongodb.name }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      {{- include "devops-app.selectorLabels" . | nindent 6 }}
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels:
        {{- include "devops-app.selectorLabels" . | nindent 8 }}
        app: {{ .Values.mongodb.name }}
    spec:
      securityContext:
        {{- toYaml .Values.mongodb.securityContext | nindent 8 }}
      containers:
      - name: {{ .Values.mongodb.name }}
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongodb.service.targetPort }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodb.config.database }}
        securityContext:
          {{- toYaml .Values.mongodb.containerSecurityContext | nindent 12 }}
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: mongodb-storage
        {{- if .Values.mongodb.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.mongodb.name }}-pvc
        {{- else }}
        emptyDir: {}  # Matches your current dev setup
        {{- end }}
{{- end }}