{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mongodb.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.mongodb.name }}
automountServiceAccountToken: false
{{- end }}