apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - name: server
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30080 # ArgoCD UI accessible on http://NODE_IP:30080
    - name: grpc
      port: 443
      protocol: TCP
      targetPort: 8080
      nodePort: 30443 # ArgoCD gRPC API accessible on http://NODE_IP:30443
  selector:
    app.kubernetes.io/name: argocd-server
