apiVersion: v2
name: devops-app
description: Enterprise DevOps Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - nodejs
  - react
  - mongodb
  - devops
maintainers:
  - name: DevOps Team
    email: devops@company.com
dependencies: []
